# Generated by Django 6.0.2 on 2026-02-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_character_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.CharField(max_length=100000),
        ),
    ]
