# Generated by Django 6.0.2 on 2026-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_character_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.TextField(max_length=100000),
        ),
    ]
