# Generated by Django 6.0.2 on 2026-03-08 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
