# Generated by Django 6.0.2 on 2026-03-08 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_message_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='update_time',
        ),
    ]
