# Generated by Django 6.0.2 on 2026-03-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_systemprompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='update_time',
        ),
    ]
