# Generated by Django 6.0.2 on 2026-03-18 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_character_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
